use dav instead of svn to upload to the distribution to workaround [INFO] java.lang.NoSuchMethodError: org.codehaus.plexus.util.cli.Commandline.createArg()Lorg/codehaus/plexus/util/cli/Arg; [INFO]  at org.apache.maven.scm.provider.svn.svnexe.command.SvnCommandLineUtils.getBaseSvnCommandLine(SvnCommandLineUtils.java:122) [INFO]  at org.apache.maven.scm.provider.svn.svnexe.command.list.SvnListCommand.createCommandLine(SvnListCommand.java:91) [INFO]  at org.apache.maven.scm.provider.svn.svnexe.command.list.SvnListCommand.executeListCommand(SvnListCommand.java:57) [INFO]  at org.apache.maven.scm.command.list.AbstractListCommand.executeCommand(AbstractListCommand.java:64) [INFO]  at org.apache.maven.scm.command.AbstractCommand.execute(AbstractCommand.java:58) [INFO]  at org.apache.maven.scm.provider.svn.AbstractSvnScmProvider.executeCommand(AbstractSvnScmProvider.java:354) [INFO]  at org.apache.maven.scm.provider.svn.AbstractSvnScmProvider.list(AbstractSvnScmProvider.java:365) [INFO]  at org.apache.maven.scm.provider.AbstractScmProvider.list(AbstractScmProvider.java:625) [INFO]  at org.apache.maven.wagon.providers.scm.ScmWagon.checkOut(ScmWagon.java:371) [INFO]  at org.apache.maven.wagon.providers.scm.ScmWagon.putInternal(ScmWagon.java:285) [INFO]  at org.apache.maven.wagon.providers.scm.ScmWagon.put(ScmWagon.java:254) [INFO]  at org.apache.maven.artifact.manager.DefaultWagonManager.putRemoteFile(DefaultWagonManager.java:317) [INFO]  at org.apache.m[INFO]  at org.apache.m[INFO]  at org.apache.m[INFO]  at org.apache.m[INFO]  at org.apache.m[INFO]  at org.apache.mifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:107) [INFO]  at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:173) [INFO]  at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)